CREATE TABLE TreasurePicture
(
	[Id] UNIQUEIDENTIFIER ROWGUIDCOL PRIMARY KEY NOT NULL DEFAULT NEWSEQUENTIALID(),
	[TreasureId] INT NOT NULL, 
	[FileName] NVARCHAR(120) NOT NULL, 
	[ContentType] NVARCHAR(120) NOT NULL,
	[FileStream] VARBINARY(MAX) FILESTREAM NULL, 
	INDEX IX_TreasurePicture_TreasureId ON ([TreasureId])
)