CREATE TABLE Attachment
(
	[Id] UNIQUEIDENTIFIER ROWGUIDCOL PRIMARY KEY NOT NULL DEFAULT NEWSEQUENTIALID(),
	[FileName] NVARCHAR(120) NOT NULL, 
	[ContentType] NVARCHAR(120) NOT NULL,
	[FileStream] VARBINARY(MAX) FILESTREAM NULL
)